# Hexo配置
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# 网站
title: MingTechPro # 网站标题
subtitle: "This is MingTechPro's personal blog." # 网站副标题
description: "人性的背后是白云苍狗，愿你我都是生活的高手" # 网站描述
keywords: # 网站的关键词,支持多个关键词
author: MingTechPro # 您的名字
language: zh-CN # 语言：default(en)，zh-CN (简体中文)，zh-TW (繁体中文)
timezone: "Asia/Shanghai" # 设置网站时区，Hexo 默认使用您电脑的时区（查询时区：https://en.wikipedia.org/wiki/List_of_tz_database_time_zones）

# 网站链接
## 例如，如果您使用Git Hub Page，请将url设置为 'https://username.github.io/project'
url: https://mingtechpro.top
permalink: posts/:abbrlink/
permalink_defaults:
pretty_urls:
  trailing_index: false # 设置为false将从永久链接中删除尾随索引html
  trailing_html: false # 设置为false将从永久链接中删除尾随html

# 目录
source_dir: source # 资源文件夹，这个文件夹用来存放内容
public_dir: public # 公共文件夹，这个文件夹用于存放生成的站点文件
tag_dir: tags # 标签文件夹
archive_dir: archives # 归档文件夹
category_dir: categories # 分类文件夹
code_dir: downloads/code # Include code 文件夹，source_dir 下的子目录
i18n_dir: :lang # 国际化（i18n）文件夹
skip_render: # 跳过指定文件的渲染。匹配到的文件将会被不做改动地复制到 public 目录中。您可使用 glob 表达式来匹配路径。

# 文章
new_post_name: :title.md # 新文章的文件名称
default_layout: post # 预设布局
titlecase: false # 把标题转换为 title case
external_link:
  enable: true # 在新选项卡中打开外部链接
  field: site # site: 对整个网站生效/post: 仅对文章生效
  exclude: "" # 需要排除的域名。主域名和子域名如 www 需分别配置
filename_case: 0 # 把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false # 显示草稿
post_asset_folder: false # 启用 资源文件夹
relative_link: false # 把链接改为与根目录的相对地址
future: true # 显示未来的文章
syntax_highlighter: highlight.js # 代码块高亮的设置
# 代码块的设置
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ""

# 首页设置
index_generator:
  path: "/" # path 默认的博客索引页的根路径
  per_page: 8 # 每页显示的帖子，(0 = 关闭分页功能)
  order_by: -date # 默认情况下按日期降序排序

# 类别 & 标签 设置
default_category: uncategorized # 默认分类
category_map: # 分类别名
tag_map: # 标签别名

# 元数据元素 设置
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# 日期 / 时间格式 设置
## Hexo使用Moment js来解析和显示日期
## 可以自定义日期格式
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD # 日期格式
time_format: HH:mm:ss # 时间格式
## 更新的选项支持 'mtime', 'date', 'empty'
updated_option: "mtime"

# 分页设置
per_page: 8 # 每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page # 分页目录

# 主题设置
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly # 设置当前主题名称。值为false时禁用主题

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ""

# 代码程序图设置
kramed:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

# 本地搜索设置
search:
  path: search.xml
  field: post
  content: true
  format: html

# 短链接设置
abbrlink:
  alg: crc32      #支持 crc16(默认) 或者 crc32
  rep: hex        #支持 dec(默认) 或者 hex
  drafts: false   #(true)流程草搞,(false)不处理草稿. false(默认) 
  # 从目录树生成类别
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
     enable: true  #true(默认)
     depth:        #3(默认)
     over_write: false 
  auto_title: true #启用自动标题，可以按路径自动填充标题
  auto_date: false #启用自动日期，它可以自动填写日期的时间今天
  force: false #在这种模式下，插件将忽略缓存并计算每个帖子的abbrlink，即使它已经有了abbrlink。这只更新abbrlink而不是其他前端变量

# RSS订阅
feed:
  # 指定生成的 Feed 类型为 rss2
  type: rss2
  # 指定生成的 Feed 文件的路径和文件名
  path: feed.xml
  # 限制 Feed 中包含的文章数量为 100 篇
  limit: 100

# 音乐播放器 关闭asset_inject
aplayer:
  meting: true
  asset_inject: false